BLACKSKY_SMEAR_THRESHOLD_VALUE = 500
BLACKSKY_SMEAR_PERCENTAGE_THRESHOLD_VALUE = 20
BLACKSKY_SOBEL_THRESHOLD_VALUE = 500
BLACKSKY_LAPLACIAN_THRESHOLD_VALUE = 50
BLACKSKY_BLUR_THRESHOLD_VALUE = 1.8
DECAY_FACTOR = 0.01
COORDINATES_OF_BLOCK = (50, 50)
BLOCK_SIZE = (100, 100)
